[workspace]
resolver = "3"
members = ["excavator_backend", "excavator_backend_macros", "excavator_egui"]
default-members = ["excavator_egui"]

[profile.dev.package."*"]
# So this one time the program got a little laggy while scrolling through a long list.
# I set opt-level = 3 here to speed that up, and then kinda stuck with that setting for a while.
# The downside of that was that it utterly ballooned the time it took to recompile dependencies when they changed.
# I've switched to a more moderate setting to keep compile times convenient.
# With opt-level = 1 like this I got it rebuilt from zero in 15 minutes.
opt-level = 1

[workspace.dependencies]
# For convenience, we've gathered every dependency in the workspace (not counting intra-workspace ones) in this single place, and lightly categorized them.

# Small and handy things
anyhow = "1.0.104"
undo_2 = "0.2.1"
yoke = "0.8.3"
zerocopy = { version = "0.8.56", features = ["std"] }
zerocopy-derive = "0.8.56"

# Big and handy things
bevy_ecs = { version = "0.19.1", default-features = false }
serde = "1.0.229"

# GUI
# would be egui 0.36.1 if ltreeview updated faster... oh well
eframe = { version = "0.35.0", features = ["persistence"] }
egui = "0.35.0"
rfd = "0.17.2"

# For procedural macros
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.3"
