[package]
name = "excavator_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
excavator_backend.path = "../excavator_backend"

# Data structures and whatnot
thunderdome.workspace = true
yoke.workspace = true

# Miscellaneous
anyhow.workspace = true
image.workspace = true
parking_lot.workspace = true
serde.workspace = true

# GUI
eframe.workspace = true
egui.workspace = true
egui_ltreeview.workspace = true
rfd.workspace = true
