[package]
name = "excavator_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
excavator_backend.path = "../excavator_backend"

# Data structures and whatnot
yoke.workspace = true

# Miscellaneous
anyhow.workspace = true
serde.workspace = true

# GUI
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
