[package]
name = "excavator_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bevy_ecs = "0.19.0"
bstr = { workspace = true }
image = { workspace = true }
lexical-sort = "0.3.1"
serde = { workspace = true }
zerocopy = { version = "0.8.39", features = ["std"] }
zerocopy-derive = "0.8.39"
